# Generated by Django 3.0.9 on 2022-05-23 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Input name author', max_length=100, verbose_name='Author name')),
                ('last_name', models.CharField(help_text='Input family name author', max_length=100, verbose_name='Author family name')),
                ('date_of_birth', models.DateField(blank=True, help_text='Input date of birth', null=True, verbose_name='Birth date')),
                ('date_of_death', models.DateField(blank=True, help_text='Input date of death', null=True, verbose_name='Death date')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Input title of the book', max_length=200, verbose_name='Name of book')),
                ('summary', models.TextField(help_text='Input summary of the book', max_length=1000, verbose_name='Short text of the book')),
                ('isbn', models.CharField(help_text='Only 13 symbols', max_length=13, verbose_name='ISBN of the book')),
                ('author', models.ManyToManyField(help_text=' Choose author of the book', to='catalog.Author', verbose_name='Author of book')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input genre of the book', max_length=200, verbose_name='Genre book')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input language of the book', max_length=20, verbose_name='Book language')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input status of book', max_length=20, verbose_name='Status exemplar of book')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_num', models.CharField(help_text='Input inentary number', max_length=20, null=True, verbose_name='Inventary humber')),
                ('inprint', models.CharField(help_text='Input publishing and year', max_length=200, verbose_name='Publishing')),
                ('due_back', models.DateField(blank=True, help_text='Input end of status', null=True, verbose_name='Date of status')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Book')),
                ('status', models.ForeignKey(help_text='Change status exemplar', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Status', verbose_name='Status exemplar')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text=' Choose genre of the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Genre', verbose_name='Genre of book'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text=' Choose language of the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Language', verbose_name='Language of book'),
        ),
    ]
